### ISSUE TITLE
Consider adding  Rux code to view_component 3

### ISSUE THREAD

**Issue by reeganviljoen** [camertron/rux-rails#11]
@camertron Look here, thier is a feature request to add jsx style templates to view_component https://github.com/ViewComponent/view_component/issues/1756

**Comment by camertron** [comment]
Cool, I will check it out 😄

**Comment by reeganviljoen** [comment]
@camertron I see your response on the view_component repo and I think to get it to a point where it can be ready we first need to add view_component 3 support, and then a possible re-write to make it work more like slim under the hood, I would love to help in getting that done if you would be interested

**Comment by camertron** [comment]
I just added view_component v3 support yesterday (see #12). Are you familiar with how Slim works under the hood, because I'm definitely not 😅 I would gladly review a refactor PR if you're willing to take it on though! I think you'll just need to change the emitter part, i.e. the part that generates Ruby code.

**Comment by camertron** [comment]
Hey @reeganviljoen, I'm going to close this for now. Feel free to reopen if necessary.

**Comment by reeganviljoen** [comment]
@camertron I see I remember you said you would be experimenting with rux inside of view_component, how did that go?

**Comment by camertron** [comment]
@reeganviljoen ah apologies for the misunderstanding. Without serious effort that I'm not able to expend right now, rux will probably never make it into view_component. Integrating them would be fairly straightforward, but even I, a maintainer of ViewComponent, would never merge the resulting PR because of the monkeypatches I mentioned in https://github.com/ViewComponent/view_component/issues/1756. Sourcemapping and backtraces are still a problem too.

**Comment by reeganviljoen** [comment]
@camertron after some investigation it turns out slim usses [temple](https://github.com/judofyr/temple) to avoid monkey patching ruby and [tilt](https://github.com/rtomayko/tilt) to make its usage generic, maybe implementing that into Rux would be a good addition to rux

**Comment by camertron** [comment]
@reeganviljoen oh man, that's a great idea! I don't think temple or tilt would help avoid the monkeypatches, but it sounds like especially temple could speed up template rendering. Thanks!
