### ISSUE TITLE
Rux’s speed

### ISSUE THREAD

**Issue by nicieja** [camertron/rux-rails#5]
A big fan of the concept here. I’ve used the gem in my project and the view using the component started to render in 100-150ms instead of the usual ~30ms I got with when I used a Slim template in development. Is that 3-5x decrease in speed expected? If yes, is there anything that can be done to make Rux faster?

**Comment by camertron** [comment]
Hey @nicieja, thanks for giving Rux a try :)

I must confess that all my efforts with Rux so far have been focused on simply getting it to work, and no attention has been paid to performance. If memory serves, Slim was explicitly designed with performance in mind, so I'm not surprised you're seeing such a disparity in performance between the two engines.

> Is there anything that can be done to make Rux faster?

I'm sure there is, but I would have to do some benchmarking to be sure. Off the top of my head, it's probably worthwhile to look at how many times `Rux.create_buffer` is called, since each call will allocate a new `ActiveSupport::SafeBuffer`.

Here's an example from the rux docs:

```ruby
Rux.tag("span") {
  Rux.create_buffer.tap { |_rux_buf_,|
    _rux_buf_ << @first_name
    _rux_buf_ << " "
    _rux_buf_ << @last_name
  }.to_s
}
```

It's not entirely obvious from this example, but Rux will create a new buffer every time the code transitions from Rux -> Ruby, i.e. when encountering curly braces. Rails' ActionVIew uses a single global output buffer, which is probably what Rux should do too. Since `call` is designed to return a string, I don't think Rux can use ActionView's output buffer. However, Rux could create a single buffer within the context of the `call` method and append to it at every nesting level.

Another thing to think about: Rux uses `ActiveSupport::SafeBuffer` because I wanted to use the same HTML safety mechanisms Rails already provides. We could probably come up with a more performant implementation. We might also be able to distinguish between safe and unsafe appends like ERB does, which could skip escaping unnecessarily.

**Comment by devaayushraj** [comment]
@camertron Thank you so much for making something like this. 
I am new to Rails, I am loving it.

I am put for by ERB tags. I am not a big fan for composing components, cause rarely I am going to need the use, for most case partials serves the purpose.

I was wondering if there is any way to use is directly in views, like this:
![image](https://user-images.githubusercontent.com/84487608/188608643-eef8887d-1ec4-46e0-b091-5372debeabe8.png)

I don't want the ruby code getting messed up with ERB tag, I was looking for a way to eliminate them. Can you please guide me on this?

**Comment by camertron** [comment]
Hey @nicieja I'm just now circling back to this as there's been some additional interest in rux performance in the past few days. I put together a benchmark (see: https://github.com/camertron/rux-rails/pull/14) that actually shows rux _beating_ Slim. Are your numbers potentially coming from development, and if so, is it possible transpilation time is to blame?

**Comment by nicieja** [comment]
Hi @camertron. Nice! Yes, the numbers were from development.

**Comment by camertron** [comment]
Ok thanks @nicieja. I'm going to close this for now.
