### ISSUE TITLE
Incorrect parsing HTML data attributes

### ISSUE THREAD

**Issue by serhiihiba** [camertron/rux-rails#7]
This simple code:
```ruby
  def call
    <div class={css_class} data-controller={css_class}>
    </div>
  end
```

Generates this:
```html
<div class="ui--bentries--log--log-component" data_controller="ui--bentries--log--log-component">
</div>
```

Where `data_controller` should be `data-controller`

**Comment by camertron** [comment]
Hey @serhiijun, thanks for bringing this to my attention. I believe you're seeing this behavior because rux can render view components, which require passing HTML attributes as Ruby arguments. Since Ruby doesn't allow dashes in argument names, rux replaces them with underscores. However rux probably shouldn't do that for HTML tags.

I just looked into this and published v1.1.1 of the rux gem. Let me know if you run into any additional issues.
